# Generated by Django 5.0.4 on 2024-05-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbcClient',
            fields=[
                ('abc_client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', models.CharField(max_length=45)),
                ('created_date', models.DateTimeField()),
                ('modified_by', models.CharField(blank=True, max_length=45, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'abc_client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AbcResource',
            fields=[
                ('abc_resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_name', models.CharField(max_length=45)),
                ('max_number_of_resources', models.BigIntegerField()),
                ('current_number_of_resources', models.BigIntegerField()),
                ('created_by', models.CharField(max_length=45)),
                ('created_date', models.DateTimeField()),
                ('modified_by', models.CharField(blank=True, max_length=45, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'abc_resource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('access_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('action', models.CharField(max_length=45)),
                ('table_name', models.CharField(blank=True, max_length=45, null=True)),
                ('field_name', models.CharField(blank=True, max_length=45, null=True)),
                ('screen_name', models.CharField(blank=True, max_length=45, null=True)),
                ('log_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'access_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, max_length=45, null=True)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=45)),
                ('postal_code', models.CharField(max_length=45)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', models.CharField(max_length=45)),
                ('created_date', models.DateTimeField()),
                ('modified_by', models.CharField(blank=True, max_length=45, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientContacts',
            fields=[
                ('client_contacts_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(max_length=45)),
                ('created_date', models.DateTimeField()),
                ('modified_by', models.CharField(blank=True, max_length=45, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'client_contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_address', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', models.CharField(max_length=45)),
                ('created_date', models.DateTimeField()),
                ('modified_by', models.CharField(blank=True, max_length=45, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_name', models.CharField(max_length=45)),
                ('max_item_capacity', models.BigIntegerField()),
                ('created_by', models.CharField(max_length=45)),
                ('created_date', models.DateTimeField()),
                ('modified_by', models.CharField(blank=True, max_length=45, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('resource_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=45)),
                ('created_by', models.CharField(max_length=45)),
                ('created_date', models.DateTimeField()),
                ('modified_by', models.CharField(blank=True, max_length=45, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'resource_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('storage_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=45)),
                ('created_by', models.CharField(max_length=45)),
                ('created_date', models.DateTimeField()),
                ('modified_by', models.CharField(blank=True, max_length=45, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'storage_type_id',
                'managed': False,
            },
        ),
    ]
